#!/usr/bin/env bash
#------------------------------------------------------------------------------
#
#                           Sensibility Analysis
#
#                             Graduation work
#
#------------------------------------------------------------------------------
# @ Manon Cornet

julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage true --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu3 --plot_file_name plot_simu3 --simu_name simu_spanning_tree_3

# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu0 --plot_file_name plot_simu0 --simu_name simu_spanning_tree_0

# julia --project src/main_bilevel.jl --radiality spanning_tree --EV true --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu1 --plot_file_name plot_simu1 --simu_name simu_spanning_tree_1

# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP true --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu2 --plot_file_name plot_simu2 --simu_name simu_spanning_tree_2

# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage true --Storage_cost 300 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu3 --plot_file_name plot_simu3 --simu_name simu_spanning_tree_3

# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage true --Storage_cost 600 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu4 --plot_file_name plot_simu4 --simu_name simu_spanning_tree_4

# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage false --Storage_cost 500 --network_reconfig true --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu5 --plot_file_name plot_simu5 --simu_name simu_spanning_tree_5

# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel false --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu6 --plot_file_name plot_simu6 --simu_name simu_spanning_tree_6
# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.0 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu7 --plot_file_name plot_simu7 --simu_name simu_spanning_tree_7
# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.8 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu8 --plot_file_name plot_simu8 --simu_name simu_spanning_tree_8
# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 1.6 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu9 --plot_file_name plot_simu9 --simu_name simu_spanning_tree_9
# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 300 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu10 --plot_file_name plot_simu10 --simu_name simu_spanning_tree_10
# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 600 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu11 --plot_file_name plot_simu11 --simu_name simu_spanning_tree_11
# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.6 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu12 --plot_file_name plot_simu12 --simu_name simu_spanning_tree_12
# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.9 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu13 --plot_file_name plot_simu13 --simu_name simu_spanning_tree_13
# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.2 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu14 --plot_file_name plot_simu14 --simu_name simu_spanning_tree_14
# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.3 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu15 --plot_file_name plot_simu15 --simu_name simu_spanning_tree_15
# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.2 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu16 --plot_file_name plot_simu16 --simu_name simu_spanning_tree_16
# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.3 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu17 --plot_file_name plot_simu17 --simu_name simu_spanning_tree_17
# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 120 --weight_I 0.01 --network_graph_name network_graph_simu18 --plot_file_name plot_simu18 --simu_name simu_spanning_tree_18
# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 160 --weight_I 0.01 --network_graph_name network_graph_simu19 --plot_file_name plot_simu19 --simu_name simu_spanning_tree_19
# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.001 --network_graph_name network_graph_simu20 --plot_file_name plot_simu20 --simu_name simu_spanning_tree_20
# julia --project src/main_bilevel.jl --radiality spanning_tree --EV false --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.1 --network_graph_name network_graph_simu21 --plot_file_name plot_simu21 --simu_name simu_spanning_tree_21
