#!/usr/bin/env bash
#------------------------------------------------------------------------------
#
#                           Sensibility Analysis
#
#                             Graduation work
#
#------------------------------------------------------------------------------
# @ Manon Cornet

julia --project src/main_bilevel.jl --EV false --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu0 --plot_file_name plot_simu0 --simu_name simu_0
julia --project src/main_bilevel.jl --EV true --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu1 --plot_file_name plot_simu1 --simu_name simu_1
julia --project src/main_bilevel.jl --EV true --EHP false --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu2 --plot_file_name plot_simu2 --simu_name simu_2
julia --project src/main_bilevel.jl --EV true --EHP true --storage false --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu3 --plot_file_name plot_simu3 --simu_name simu_3
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 500 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu4 --plot_file_name plot_simu4 --simu_name simu_4
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 300 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu5 --plot_file_name plot_simu5 --simu_name simu_5
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu6 --plot_file_name plot_simu6 --simu_name simu_6
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig false --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu7 --plot_file_name plot_simu7 --simu_name simu_7
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu8 --plot_file_name plot_simu8 --simu_name simu_8
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel true --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu9 --plot_file_name plot_simu9 --simu_name simu_9
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu10 --plot_file_name plot_simu10 --simu_name simu_10
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 0.4 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu11 --plot_file_name plot_simu11 --simu_name simu_11
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 0.0 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu12 --plot_file_name plot_simu12 --simu_name simu_12
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 0.8 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu13 --plot_file_name plot_simu13 --simu_name simu_13
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 1.6 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu14 --plot_file_name plot_simu14 --simu_name simu_14
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 1.6 --PVC 500 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu15 --plot_file_name plot_simu15 --simu_name simu_15
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 1.6 --PVC 300 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu16 --plot_file_name plot_simu16 --simu_name simu_16
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 1.6 --PVC 600 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu17 --plot_file_name plot_simu17 --simu_name simu_17
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 1.6 --PVC 600 --EIC 0.3 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu18 --plot_file_name plot_simu18 --simu_name simu_18
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 1.6 --PVC 600 --EIC 0.6 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu19 --plot_file_name plot_simu19 --simu_name simu_19
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 1.6 --PVC 600 --EIC 0.9 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu20 --plot_file_name plot_simu20 --simu_name simu_20
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 1.6 --PVC 600 --EIC 0.9 --EEC 0.1 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu21 --plot_file_name plot_simu21 --simu_name simu_21
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 1.6 --PVC 600 --EIC 0.9 --EEC 0.2 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu22 --plot_file_name plot_simu22 --simu_name simu_22
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 1.6 --PVC 600 --EIC 0.9 --EEC 0.3 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu23 --plot_file_name plot_simu23 --simu_name simu_23
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 1.6 --PVC 600 --EIC 0.9 --EEC 0.3 --DSOEC 0.1 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu24 --plot_file_name plot_simu24 --simu_name simu_24
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 1.6 --PVC 600 --EIC 0.9 --EEC 0.3 --DSOEC 0.2 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu25 --plot_file_name plot_simu25 --simu_name simu_25
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 1.6 --PVC 600 --EIC 0.9 --EEC 0.3 --DSOEC 0.3 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu26 --plot_file_name plot_simu26 --simu_name simu_26
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 1.6 --PVC 600 --EIC 0.9 --EEC 0.3 --DSOEC 0.3 --GCC 80 --weight_I 0.01 --network_graph_name network_graph_simu27 --plot_file_name plot_simu27 --simu_name simu_27
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 1.6 --PVC 600 --EIC 0.9 --EEC 0.3 --DSOEC 0.3 --GCC 120 --weight_I 0.01 --network_graph_name network_graph_simu28 --plot_file_name plot_simu28 --simu_name simu_28
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 1.6 --PVC 600 --EIC 0.9 --EEC 0.3 --DSOEC 0.3 --GCC 160 --weight_I 0.01 --network_graph_name network_graph_simu29 --plot_file_name plot_simu29 --simu_name simu_29
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 1.6 --PVC 600 --EIC 0.9 --EEC 0.3 --DSOEC 0.3 --GCC 160 --weight_I 0.01 --network_graph_name network_graph_simu30 --plot_file_name plot_simu30 --simu_name simu_30
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 1.6 --PVC 600 --EIC 0.9 --EEC 0.3 --DSOEC 0.3 --GCC 160 --weight_I 0.001 --network_graph_name network_graph_simu31 --plot_file_name plot_simu31 --simu_name simu_31
julia --project src/main_bilevel.jl --EV true --EHP true --storage true --Storage_cost 600 --network_reconfig true --bilevel false --PV_CAPA 1.6 --PVC 600 --EIC 0.9 --EEC 0.3 --DSOEC 0.3 --GCC 160 --weight_I 0.1 --network_graph_name network_graph_simu32 --plot_file_name plot_simu32 --simu_name simu_32
